//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodMovies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoodMovies.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginView_Button_Login {
            get {
                return ResourceManager.GetString("LoginView_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string LoginView_Label_Email {
            get {
                return ResourceManager.GetString("LoginView_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged in.
        /// </summary>
        internal static string LoginView_Label_KeepMeLoggedIn {
            get {
                return ResourceManager.GetString("LoginView_Label_KeepMeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string LoginView_Label_Password {
            get {
                return ResourceManager.GetString("LoginView_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginView_TextBox_Email_Hint {
            get {
                return ResourceManager.GetString("LoginView_TextBox_Email_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginView_TextBox_Password_Hint {
            get {
                return ResourceManager.GetString("LoginView_TextBox_Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit App.
        /// </summary>
        internal static string MainView_Button_Exit {
            get {
                return ResourceManager.GetString("MainView_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainView_Button_Help {
            get {
                return ResourceManager.GetString("MainView_Button_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string MainView_Chip_LogOut {
            get {
                return ResourceManager.GetString("MainView_Chip_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string MainView_Menubar_Button_Favourites {
            get {
                return ResourceManager.GetString("MainView_Menubar_Button_Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string MainView_Menubar_Button_Results {
            get {
                return ResourceManager.GetString("MainView_Menubar_Button_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MainView_Menubar_Button_Search {
            get {
                return ResourceManager.GetString("MainView_Menubar_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string MainView_Menubar_Button_Users {
            get {
                return ResourceManager.GetString("MainView_Menubar_Button_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WatchList.
        /// </summary>
        internal static string MainView_Menubar_Button_WatchList {
            get {
                return ResourceManager.GetString("MainView_Menubar_Button_WatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string MovieCardView_Button_Language {
            get {
                return ResourceManager.GetString("MovieCardView_Button_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        internal static string MovieCardView_Button_Popularity {
            get {
                return ResourceManager.GetString("MovieCardView_Button_Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released:.
        /// </summary>
        internal static string MovieCardView_Button_Released {
            get {
                return ResourceManager.GetString("MovieCardView_Button_Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Trailer.
        /// </summary>
        internal static string MovieCardView_Button_ViewTrailer {
            get {
                return ResourceManager.GetString("MovieCardView_Button_ViewTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Votes:.
        /// </summary>
        internal static string MovieCardView_Button_VotesCount {
            get {
                return ResourceManager.GetString("MovieCardView_Button_VotesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favourites.
        /// </summary>
        internal static string MovieCardView_ToggleButton_AddToFavourites {
            get {
                return ResourceManager.GetString("MovieCardView_ToggleButton_AddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to WatchList.
        /// </summary>
        internal static string MovieCardView_ToggleButton_AddToWatchList {
            get {
                return ResourceManager.GetString("MovieCardView_ToggleButton_AddToWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string RegisterView_Button_CreateAccount {
            get {
                return ResourceManager.GetString("RegisterView_Button_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB API Key:.
        /// </summary>
        internal static string RegisterView_Label_ApiKey {
            get {
                return ResourceManager.GetString("RegisterView_Label_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string RegisterView_Label_Email {
            get {
                return ResourceManager.GetString("RegisterView_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string RegisterView_Label_FirstName {
            get {
                return ResourceManager.GetString("RegisterView_Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string RegisterView_Label_Password {
            get {
                return ResourceManager.GetString("RegisterView_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        internal static string RegisterView_Label_SurName {
            get {
                return ResourceManager.GetString("RegisterView_Label_SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB API Key.
        /// </summary>
        internal static string RegisterView_TextBox_ApiKey_Hint {
            get {
                return ResourceManager.GetString("RegisterView_TextBox_ApiKey_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterView_TextBox_Email_Hint {
            get {
                return ResourceManager.GetString("RegisterView_TextBox_Email_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string RegisterView_TextBox_FirstName_Hint {
            get {
                return ResourceManager.GetString("RegisterView_TextBox_FirstName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegisterView_TextBox_Password_Hint {
            get {
                return ResourceManager.GetString("RegisterView_TextBox_Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string RegisterView_TextBox_SurName_Hint {
            get {
                return ResourceManager.GetString("RegisterView_TextBox_SurName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        internal static string SearchView_Filter_ComboBox_Everything {
            get {
                return ResourceManager.GetString("SearchView_Filter_ComboBox_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I pick ....
        /// </summary>
        internal static string SearchView_Filter_ComboBox_Hint {
            get {
                return ResourceManager.GetString("SearchView_Filter_ComboBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        internal static string SearchView_Filter_ComboBox_NowPlaying {
            get {
                return ResourceManager.GetString("SearchView_Filter_ComboBox_NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        internal static string SearchView_Filter_ComboBox_Popular {
            get {
                return ResourceManager.GetString("SearchView_Filter_ComboBox_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Rated.
        /// </summary>
        internal static string SearchView_Filter_ComboBox_TopRated {
            get {
                return ResourceManager.GetString("SearchView_Filter_ComboBox_TopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        internal static string SearchView_Filter_ComboBox_Upcoming {
            get {
                return ResourceManager.GetString("SearchView_Filter_ComboBox_Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I feel ....
        /// </summary>
        internal static string SearchView_Genre_ComboBox_Hint {
            get {
                return ResourceManager.GetString("SearchView_Genre_ComboBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        internal static string SearchView_Genre_ComboBoxItem_Everything {
            get {
                return ResourceManager.GetString("SearchView_Genre_ComboBoxItem_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        internal static string SearchView_Genre_ComboBoxItem_Happy {
            get {
                return ResourceManager.GetString("SearchView_Genre_ComboBoxItem_Happy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loved.
        /// </summary>
        internal static string SearchView_Genre_ComboBoxItem_Loved {
            get {
                return ResourceManager.GetString("SearchView_Genre_ComboBoxItem_Loved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scared.
        /// </summary>
        internal static string SearchView_Genre_ComboBoxItem_Scared {
            get {
                return ResourceManager.GetString("SearchView_Genre_ComboBoxItem_Scared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrilled.
        /// </summary>
        internal static string SearchView_Genre_ComboBoxItem_Thrilled {
            get {
                return ResourceManager.GetString("SearchView_Genre_ComboBoxItem_Thrilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string SearchView_Source_ComboBox_Favourites {
            get {
                return ResourceManager.GetString("SearchView_Source_ComboBox_Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source ....
        /// </summary>
        internal static string SearchView_Source_ComboBox_Hint {
            get {
                return ResourceManager.GetString("SearchView_Source_ComboBox_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string SearchView_Source_ComboBox_Online {
            get {
                return ResourceManager.GetString("SearchView_Source_ComboBox_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WatchList.
        /// </summary>
        internal static string SearchView_Source_ComboBox_WatchList {
            get {
                return ResourceManager.GetString("SearchView_Source_ComboBox_WatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        internal static string SearchView_TextBox_Actor {
            get {
                return ResourceManager.GetString("SearchView_TextBox_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SearchView_TextBox_Title {
            get {
                return ResourceManager.GetString("SearchView_TextBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing User.
        /// </summary>
        internal static string StartPageView_Button_ExistingUser {
            get {
                return ResourceManager.GetString("StartPageView_Button_ExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string StartPageView_Button_NewUser {
            get {
                return ResourceManager.GetString("StartPageView_Button_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new User.
        /// </summary>
        internal static string UserControlView_Button_AddNewUser {
            get {
                return ResourceManager.GetString("UserControlView_Button_AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as current User.
        /// </summary>
        internal static string UserControlView_DataGrid_Button_SetAsCurrentUser {
            get {
                return ResourceManager.GetString("UserControlView_DataGrid_Button_SetAsCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string UserControlView_DataGrid_Header_Action {
            get {
                return ResourceManager.GetString("UserControlView_DataGrid_Header_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string UserControlView_DataGrid_Header_ApiKey {
            get {
                return ResourceManager.GetString("UserControlView_DataGrid_Header_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string UserControlView_DataGrid_Header_FirstName {
            get {
                return ResourceManager.GetString("UserControlView_DataGrid_Header_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string UserControlView_DataGrid_Header_SurName {
            get {
                return ResourceManager.GetString("UserControlView_DataGrid_Header_SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User.
        /// </summary>
        internal static string UserControlView_Label_CurrentUser {
            get {
                return ResourceManager.GetString("UserControlView_Label_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string UserControlView_Label_FirstName {
            get {
                return ResourceManager.GetString("UserControlView_Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string UserControlView_Label_SurName {
            get {
                return ResourceManager.GetString("UserControlView_Label_SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB API Key.
        /// </summary>
        internal static string UserControlView_Label_TMBDB_ApiKey {
            get {
                return ResourceManager.GetString("UserControlView_Label_TMBDB_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a new User please first obtain an Api key from www.themoviedb.org.
        /// </summary>
        internal static string UserControlView_Label_WarningApiKey {
            get {
                return ResourceManager.GetString("UserControlView_Label_WarningApiKey", resourceCulture);
            }
        }
    }
}
